# Generated by Django 4.0.4 on 2022-08-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('apellido', models.TextField(blank=True, null=True)),
                ('sexo_id', models.TextField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('categoria', models.TextField(blank=True, null=True)),
                ('sucursal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('saldo', models.IntegerField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuentas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('apellido', models.TextField(blank=True, null=True)),
                ('sexo_id', models.TextField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('categoria', models.TextField(blank=True, null=True)),
                ('sucursal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('calle', models.TextField(blank=True, null=True)),
                ('altura', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sucursales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ids',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente_id', models.IntegerField(blank=True)),
                ('username', models.TextField(blank=True)),
                ('tipo', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ids',
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(null=True)),
                ('fecha', models.TextField(null=True)),
                ('importe', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'movimientos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente_id', models.TextField(blank=True, null=True)),
                ('monto', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prestamos',
            },
        ),
    ]
