# Generated by Django 4.0.4 on 2022-08-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(blank=True)),
                ('cliente_dni', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'dni',
                'managed': False,
            },
        ),
    ]
