# Generated by Django 4.0.4 on 2022-08-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dni',
            options={},
        ),
    ]
