# Generated by Django 4.0.4 on 2022-08-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_dni_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dni',
            name='cliente_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='dni',
            table=None,
        ),
    ]
