# Generated by Django 4.0.4 on 2022-08-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_dni_cliente_id_alter_dni_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dni',
            table='dni',
        ),
    ]
