# Generated by Django 4.0.4 on 2022-08-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_dni_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dni',
        ),
    ]
