# Generated by Django 4.0.4 on 2022-08-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.TextField(blank=True)),
                ('cliente_dni', models.IntegerField(blank=True)),
            ],
        ),
    ]
