# Generated by Django 4.0.6 on 2022-08-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.TextField(blank=True)),
                ('username', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Dni',
        ),
    ]
